package cl.model.pojos;
// Generated 26/12/2015 12:31:23 PM by Hibernate Tools 3.6.0



/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String descripcion;
     private float valor;

    public Productos() {
    }

    public Productos(String codigo, String nombre, String descripcion, float valor) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.valor = valor;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }




}


